### ISSUE TITLE
Pret data set review

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/ons-faster-economic-indicators#28]
Review the dataset, providing suggestion for changes.

1. Look at the csv
2. Look at the json file
3. Look at the associated concept schemes if they are separate
4. Validate the serialised output folder
5. Provide the feedback as a comment on github

**Comment by sazzadur-ons** [comment]
pret.json
================
"Value" column:
"from_existing": "https://purl.org/csv-cubed/resources/measures#indexed-sales-value"
Warning: Value is not accepted. Valid values: "http://gss-data.org.uk/def/measure/count", "http://gss-data.org.uk/def/measure/travel-time", "http://gss-data.org.uk/def/measure/expenditure", "http://gss-data.org.uk/def/measure/sales", "http://gss-data.org.uk/def/measure/median-costs", "http://gss-data.org.uk/def/measure/median-floor-area", "http://gss-data.org.uk/def/measure/median-income", "http://gss-data.org.uk/def/trade/measure/monetary-value", "http://gss-data.org.uk/def/measure/tariff", "http://gss-data.org.uk/def/measure/ranks", "http://gss-data.org.uk/def/trade/measure/index".

**Comment by sazzadur-ons** [comment]
pret.csv
=========
It is not clear why "Value" column has many decimal places.

**Comment by sazzadur-ons** [comment]
csvcubed build failed:
=================
2023-01-27 09:50:31,026 - csvcubed.models.cube.cube - CRITICAL - Traceback (most recent call last):
  File "/Users/sazzadurrahman/projects/ons-fei/lib/python3.10/site-packages/csvcubed/models/cube/cube.py", line 75, in validate
    errors += self.pydantic_validation()
  File "/Users/sazzadurrahman/projects/ons-fei/lib/python3.10/site-packages/csvcubed/models/pydanticmodel.py", line 78, in pydantic_validation
    validated_model_or_errors = self._to_pydantic_dataclass_or_validation_errors()
  File "/Users/sazzadurrahman/projects/ons-fei/lib/python3.10/site-packages/csvcubed/models/pydanticmodel.py", line 63, in _to_pydantic_dataclass_or_validation_errors
    pydantic_class_constructor = self.__class__._get_pydantic_constructor()
  File "/Users/sazzadurrahman/projects/ons-fei/lib/python3.10/site-packages/csvcubed/models/pydanticmodel.py", line 49, in _get_pydantic_constructor
    _map_class_to_pydantic_constructor[cls] = pydantic.dataclasses.dataclass(
  File "pydantic/dataclasses.py", line 231, in pydantic.dataclasses.dataclass
  File "pydantic/dataclasses.py", line 207, in pydantic.dataclasses.dataclass.wrap
  File "/opt/anaconda3/lib/python3.10/dataclasses.py", line 1185, in dataclass
    return wrap(cls)
  File "/opt/anaconda3/lib/python3.10/dataclasses.py", line 1176, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
  File "/opt/anaconda3/lib/python3.10/dataclasses.py", line 1025, in _process_class
    _init_fn(all_init_fields,
  File "/opt/anaconda3/lib/python3.10/dataclasses.py", line 546, in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'columns' follows default argument
 (log.py:98)
2023-01-27 09:50:31,027 - csvcubed.cli.build - ERROR - Validation Error: A validation error occurred when validating the cube: 'non-default argument 'columns' follows default argument'. (build.py:96)
2023-01-27 09:50:31,027 - csvcubed.cli.build - ERROR - Validation Error: A validation error occurred when validating the cube: 'An error occurred and validation Failed to Complete'. (build.py:96)
2023-01-27 09:50:31,028 - csvcubed.cli.build - WARNING - Schema Validation Error: $.columns.Value - Unable to identify {'type': 'observations', 'data_type': 'decimal', 'measure': {'label': 'indexed sales', 'description': 'indexed weekly sales indexe…

    If you meant to declare 'This column represents a dimension of the cube', then:
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)
        $.type - 'dimension' was expected

    If you meant to declare 'This column represents an attribute (with resource values) of the cube (creating a new attribute)', then:
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)
        $.type - 'attribute' was expected

    If you meant to declare 'This column represents an attribute (with resource values) of the cube (reusing an existing attribute definition)', then:
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)
        $.type - 'attribute' was expected

    If you meant to declare 'This column represents an attribute (with literal values) of the cube', then:
        - Additional properties are not allowed ('measure', 'unit' were unexpected)
        $.type - 'attribute' was expected

    If you meant to declare 'This column represents the phenomenon which has been measured (defining new measures)', then:
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)
        $.type - 'measures' was expected

    If you meant to declare 'This column represents the phenomenon which has been measured (reusing existing measure definitions)', then:
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)
        $.type - 'measures' was expected

    If you meant to declare 'This column holds observed/recorded values', then:
        $.measure.from_existing - 'https://purl.org/csv-cubed/resources/measures#indexed-sales-value' is not recognised by csvcubed.

    If you meant to declare 'This column represents the unit of measure in which observations were recorded (defining new units)', then:
        $.type - 'units' was expected
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)

    If you meant to declare 'This column represents the unit of measure in which observations were recorded (reusing existing unit definitions)', then:
        $.type - 'units' was expected
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)

    If you meant to declare 'This column will be present in the CSV but will not be converted to RDF', then:
        - {'type': 'observations', 'data_type': 'decimal', 'measure': {'label': 'indexed sales', 'description': 'indexed weekly sales indexed ((Friday 3 Januar…
        - False was expected (build.py:101)
2023-01-27 09:50:31,029 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[0].same_as - None is not of type 'string' (build.py:101)
2023-01-27 09:50:31,029 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[0].uri_safe_identifier_override - None is not of type 'string' (build.py:101)
2023-01-27 09:50:31,029 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[1].same_as - None is not of type 'string' (build.py:101)
2023-01-27 09:50:31,029 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[1].uri_safe_identifier_override - None is not of type 'string' (build.py:101)
2023-01-27 09:50:31,029 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[2].same_as - None is not of type 'string' (build.py:101)
2023-01-27 09:50:31,029 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[2].uri_safe_identifier_override - None is not of type 'string' (build.py:101)
2023-01-27 09:50:31,029 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[3].same_as - None is not of type 'string' (build.py:101)
2023-01-27 09:50:31,029 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[3].uri_safe_identifier_override - None is not of type 'string' (build.py:101)
2023-01-27 09:50:31,029 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[4].same_as - None is not of type 'string' (build.py:101)
2023-01-27 09:50:31,030 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[4].uri_safe_identifier_override - None is not of type 'string' (build.py:101)
2023-01-27 09:50:31,030 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[5].same_as - None is not of type 'string' (build.py:101)
2023-01-27 09:50:31,030 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[5].uri_safe_identifier_override - None is not of type 'string' (build.py:101)
2023-01-27 09:50:31,030 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[6].same_as - None is not of type 'string' (build.py:101)
2023-01-27 09:50:31,030 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[6].uri_safe_identifier_override - None is not of type 'string' (build.py:101)
2023-01-27 09:50:31,030 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[7].same_as - None is not of type 'string' (build.py:101)
2023-01-27 09:50:31,030 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[7].uri_safe_identifier_override - None is not of type 'string' (build.py:101)
2023-01-27 09:50:31,030 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[8].same_as - None is not of type 'string' (build.py:101)
2023-01-27 09:50:31,030 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[8].uri_safe_identifier_override - None is not of type 'string' (build.py:101)
2023-01-27 09:50:31,030 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[9].same_as - None is not of type 'string' (build.py:101)
2023-01-27 09:50:31,030 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[9].uri_safe_identifier_override - None is not of type 'string' (build.py:101)
2023-01-27 09:50:31,031 - csvcubed.cli.build - WARNING - Schema Validation Error: $.sort - None is not of type 'object' (build.py:101)
2023-01-27 09:50:31,031 - csvcubed.cli.build - WARNING - Schema Validation Error: - 'title' is a required property (build.py:101)

**Comment by sazzadur-ons** [comment]
Build complete with warnings.
========================
2023-01-30 12:02:07,825 - csvcubed.cli.build - WARNING - Schema Validation Error: $.columns.Value - Unable to identify {'type': 'observations', 'data_type': 'decimal', 'measure': {'label': 'indexed sales', 'description': 'indexed weekly sales indexe…

    If you meant to declare 'This column represents a dimension of the cube', then:
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)
        $.type - 'dimension' was expected

    If you meant to declare 'This column represents an attribute (with resource values) of the cube (creating a new attribute)', then:
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)
        $.type - 'attribute' was expected

    If you meant to declare 'This column represents an attribute (with resource values) of the cube (reusing an existing attribute definition)', then:
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)
        $.type - 'attribute' was expected

    If you meant to declare 'This column represents an attribute (with literal values) of the cube', then:
        - Additional properties are not allowed ('measure', 'unit' were unexpected)
        $.type - 'attribute' was expected

    If you meant to declare 'This column represents the phenomenon which has been measured (defining new measures)', then:
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)
        $.type - 'measures' was expected

    If you meant to declare 'This column represents the phenomenon which has been measured (reusing existing measure definitions)', then:
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)
        $.type - 'measures' was expected

    If you meant to declare 'This column holds observed/recorded values', then:
        $.measure.from_existing - 'https://purl.org/csv-cubed/resources/measures#indexed-sales-value' is not recognised by csvcubed.

    If you meant to declare 'This column represents the unit of measure in which observations were recorded (defining new units)', then:
        $.type - 'units' was expected
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)

    If you meant to declare 'This column represents the unit of measure in which observations were recorded (reusing existing unit definitions)', then:
        $.type - 'units' was expected
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)

    If you meant to declare 'This column will be present in the CSV but will not be converted to RDF', then:
        - {'type': 'observations', 'data_type': 'decimal', 'measure': {'label': 'indexed sales', 'description': 'indexed weekly sales indexed ((Friday 3 Januar…
        - False was expected (build.py:101)
2023-01-30 12:02:07,826 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[0].same_as - None is not of type 'string' (build.py:101)
2023-01-30 12:02:07,826 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[0].uri_safe_identifier_override - None is not of type 'string' (build.py:101)
2023-01-30 12:02:07,826 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[1].same_as - None is not of type 'string' (build.py:101)
2023-01-30 12:02:07,826 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[1].uri_safe_identifier_override - None is not of type 'string' (build.py:101)
2023-01-30 12:02:07,826 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[2].same_as - None is not of type 'string' (build.py:101)
2023-01-30 12:02:07,826 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[2].uri_safe_identifier_override - None is not of type 'string' (build.py:101)
2023-01-30 12:02:07,826 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[3].same_as - None is not of type 'string' (build.py:101)
2023-01-30 12:02:07,826 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[3].uri_safe_identifier_override - None is not of type 'string' (build.py:101)
2023-01-30 12:02:07,826 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[4].same_as - None is not of type 'string' (build.py:101)
2023-01-30 12:02:07,826 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[4].uri_safe_identifier_override - None is not of type 'string' (build.py:101)
2023-01-30 12:02:07,827 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[5].same_as - None is not of type 'string' (build.py:101)
2023-01-30 12:02:07,827 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[5].uri_safe_identifier_override - None is not of type 'string' (build.py:101)
2023-01-30 12:02:07,827 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[6].same_as - None is not of type 'string' (build.py:101)
2023-01-30 12:02:07,827 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[6].uri_safe_identifier_override - None is not of type 'string' (build.py:101)
2023-01-30 12:02:07,827 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[7].same_as - None is not of type 'string' (build.py:101)
2023-01-30 12:02:07,827 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[7].uri_safe_identifier_override - None is not of type 'string' (build.py:101)
2023-01-30 12:02:07,827 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[8].same_as - None is not of type 'string' (build.py:101)
2023-01-30 12:02:07,827 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[8].uri_safe_identifier_override - None is not of type 'string' (build.py:101)
2023-01-30 12:02:07,827 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[9].same_as - None is not of type 'string' (build.py:101)
2023-01-30 12:02:07,827 - csvcubed.cli.build - WARNING - Schema Validation Error: $.concepts[9].uri_safe_identifier_override - None is not of type 'string' (build.py:101)
2023-01-30 12:02:07,827 - csvcubed.cli.build - WARNING - Schema Validation Error: $.sort - None is not of type 'object' (build.py:101)
2023-01-30 12:02:07,827 - csvcubed.cli.build - WARNING - Schema Validation Error: - 'title' is a required property (build.py:101)
Build Complete @ /Users/sazzadurrahman/projects/ons-fei/ons-fei/pret/out

**Comment by BenHowland** [comment]
Feedback:

CSV

•	Why does the value column go down to seven and eight decimals but is then whole numbers on the data from the ONS website.
•	Do we need more description form regional towns and stations. Or is that not possible, or not needed?

JSON File

•	There is no dataset_issued timeframe.
•	Creator needs to be added.
•	Good description. This near enough matches from the ONS website.
•	Good use of from_existing.
•	Is this dataset unitless?
•	We can include ONS Geography codes to the Location column to add extra detail and consistency.

**Comment by abdulkasim1** [comment]
# Pret data set review

## Dataset metadata

- [ ] Creator not provided
- [ ] Date when dataset was issued
